Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 99
  Exclude: 
    - spec/support/database_cleaner.rb
    - db/**/*
    - config/**/*
    
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db/**/*
    - config/**/*
    - app/admin/**/*
    
Style/Documentation:
  Exclude:
    - db/**/*
    
Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/**/*
    
Metrics/PerceivedComplexity:
  Max: 15
  
Metrics/CyclomaticComplexity:
  Max: 15
    
Style/BlockDelimiters:
  Exclude:
    - spec/**/*
    
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
  
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/{rails,rake,bundle}'
    - node_modules/**/*
    - Gemfile
    - Gemfile.lock
