Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 99
  Exclude: 
    - spec/support/database_cleaner.rb
    - db/**/*
    - config/**/*
    
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db/**/*
    - config/**/*
    - app/admin/**/*
    - app/controllers/concerns/**/*
    
Style/Documentation:
  Exclude:
    - db/**/*
    
Metrics/AbcSize:
  Max: 25
  Exclude:
    - app/controllers/concerns/**/*
    
Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/**/*
    - app/controllers/concerns/**/*
    
Metrics/PerceivedComplexity:
  Max: 15
  
Metrics/CyclomaticComplexity:
  Max: 15
    
Style/BlockDelimiters:
  Exclude:
    - spec/**/*
    
Style/LineEndConcatenation:
  Enabled: false
    
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
    
Lint/EmptyBlock:
  Exclude:
    - app/decorators/**/*
    
Lint/NestedMethodDefinition:
  Exclude:
    - app/controllers/concerns/**/*
  
AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'bin/{rails,rake,bundle}'
    - node_modules/**/*
    - Gemfile
    - Gemfile.lock
    - db/schema.rb
    - db/migrate/**/*
