

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'bin/{rails,rake,bundle}'
    - node_modules/**/*
    - Gemfile
    - Gemfile.lock
    - db/schema.rb
    - db/migrate/**/*
    
Layout/LineLength:
  Max: 99
  Exclude: 
    - spec/support/database_cleaner.rb
    - db/**/*
    - config/**/*
        
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
    
Lint/EmptyBlock:
  Exclude:
    - app/decorators/**/*
    - spec/factories/**/*
    
Lint/NestedMethodDefinition:
  Exclude:
    - app/controllers/concerns/**/*
    
Metrics/AbcSize:
  Max: 25
  Exclude:
    - app/controllers/concerns/**/*
    
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db/**/*
    - config/**/*
    - app/admin/**/*
    - app/my/**/*
    - app/controllers/concerns/**/*

Metrics/ClassLength:
  Max: 125
  Exclude:
    - app/models/user.rb
    - app/models/rezzable/traffic_cop.rb
    
Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/**/*
    - app/controllers/concerns/**/*
    
Metrics/PerceivedComplexity:
  Max: 15
  
Metrics/CyclomaticComplexity:
  Max: 15
    
Style/BlockDelimiters:
  Exclude:
    - spec/**/*
    
Style/Documentation:
  Exclude:
    - db/**/*
    
Style/Encoding:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false
  
Style/MultilineIfModifier:
  Enabled: false

