language: ruby
sudo: required
rvm:
  - 2.6.3
services:
  - postgresql
branches:
  only:
    - master
    - develop
env:
  - CXX=g++-4.8
  
before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

before_install:
  - npm install -g node-gyp
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
addons:
  postgresql: "9.6"   # We need the more recent version of postgresbefore_script:
  # The installation fails to create a scripts directory or copy the elasticsearch.yml
  # or logging.yml files over. THis fixes that.
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
before_script:
  - psql -c 'create database sl_app_test;' -U postgres
script: 
  - bundle exec rails webpacker:compile
  - bundle exec rails spec   # we should run all the tests in CI