language: ruby
sudo: required
rvm:
  - 2.6.3
services:
  - postgresql
branches:
  only:
    - master
    - develop
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn install
addons:
  postgresql: "9.6"   # We need the more recent version of postgresbefore_script:
  # The installation fails to create a scripts directory or copy the elasticsearch.yml
  # or logging.yml files over. THis fixes that.
before_script:
  - psql -c 'create database sl_app_test;' -U postgres
  - rails webpacker:install
script: bundle exec rspec   # we should run all the tests in CI