version: 0.2

phases:
    pre_build:
        commands:
          - echo Pre building...
          - sudo apt update -y
          - sudo apt install -y ruby-full wget
          - cd /home/ubuntu
          - wget https://bucket-name.s3.region-identifier.amazonaws.com/latest/install
          - chmod +x ./install
          - sudo ./install auto
    build:
      commands:
        - echo Building...
artifacts:
  files:
    - '**/*'
    
    