version: 0.2

phases:
    pre_build:
        - echo Pre building...
        - sudo apt update -y
        - sudo apt install ruby-full
    build:
      commands:
        - echo Building...
artifacts:
  files:
    - '**/*'