default:
  site_url: "http://example.com"
  
  visit_us_slurl: "maps.secondlife.com/secondlife/Facilis%20Quis%20Qui/148/10/2297/"
  chart:
    font: 'Arial, Helvetica, Clean, sans-serif'
  account:
    monthly_cost: 300
    discount_schedule: 
      1: 0.0
      3: 0.05
      6: 0.1
      12: 0.15
    weight_limit: 100
    delinquent_days: 365
    inactive_days: 30
  web_object:
    api_key:  <%= ENV.fetch('API_KEY') %>        # The string used as a shared key for encryption
    inactive_limit: 30              # How long from the last ping the object is considered active
  traffic_cop:
    sensor_time: 30                 # Timer for sensor sweeps
    return_message_delay: 2         # How many days to wait before greeting visitor again